from os import linesep

keywords = {
    " ?VYBER ": "SELECT ",
    " ?AKTUALIZUJ ": " UPDATE ",
    " ?VLOŽ DO ": "INSERT INTO ",
    " ?VYTVOŘ DATABÁZI ": "CREATE DATABASE ",
    " ?VYTVOŘ TABULKU ": "CREATE TABLE ",
    " ?UPRAV TABULKU": "ALTER TABLE ",
    " ?SMAŽ TABULKU ": "DROP TABLE ",
    " ?VYTVOŘ INDEX ": "CREATE INDEX ",
    " ?SMAŽ INDEX ": "DROP INDEX ",
    " Z ": " FROM ",
    " POUŽIJ ": " USE ",
    " KDE ": " WHERE ",
    " A ": " AND ",
    " NEBO ": " OR ",
    " NEPLATÍ ": " NOT ",
    " SEŘAĎ PODLE ": " ORDER BY ",
    " HODNOTY ": " VALUES ",
    " JE PRÁZDNÝ ": " NULL ",
    " NASTAV ": " SET ",
    " ?SMAŽ ": "DELETE ",
    " PŘIPOJ ZLEVA ": " LEFT JOIN ",
    " PŘIPOJ ZPRAVA ": " RIGHT JOIN ",
    " PŘIPOJ CELÉ ": " FULL JOIN ",
    " PŘIPOJ VNITŘNĚ ": " INNER JOIN ",
    " PŘIPOJ PŘIROZENĚ ": " NATURAL JOIN ",
    " PŘIPOJ ": " JOIN ",
    " NA ": "ON",
    " SESTUPNĚ": " DESC",
    " VZESTUPNĚ": " ASC",
    " VŠE ": " * ",
    f"\. |({linesep})": ";"
}
